# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff20ce6a6635d97390670c679f850c75557a6f6b0a10a890aa7c81f1b956bf96e431832e4934ab1f2543dbf08f51f6cb661842fd6e4879249ace8c267e9a1356

test:
  secret_key_base: 67d2cc819f8b1b1bc275f57a68f468ecf5bf893f7c1d1ccc00e51bf21c72fcadcfb2d461c56a64f3300bd8384cf89912ab943a49971c873a51b320cb9301fdbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
